on:
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually trigger the workflow'
        default: ''
      
  # push:
  #   branches:
  #     - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      # Install dependencies and run the scripts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline - FRED to Cloud SQL
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python fred_to_db.py

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Run data pipeline - Cloud SQL to CSV
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
        run: |
          python db_to_artifacts.py

      - name: Commit artifacts to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add artifacts"
          git push
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-csv
          path: artifacts/test.csv 

      # - name: Build Docker image
      #   run: docker build -t gcr.io/starlit-brand-297618/salesapp:0.1.0 .

      # - name: Push Docker image to GCR
      #   run: |
      #     gcloud auth configure-docker
      #     docker push gcr.io/starlit-brand-297618/salesapp:0.1.0
            