on:
  schedule:
    - cron: "39 5 * * *"

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Authenticate with Google Cloud

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '358.0.0'
          project_id: YOUR_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Install dependencies and run the scripts

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline - FRED to Cloud SQL
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}


        run: |
          fred_to_db.py

      - name: Run data pipeline - Cloud SQL to CSV
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
        run: |
          db_to_streamlit.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-csv
          path: test.csv
